#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
  echo "------------------------------------------------------------------"
  echo "📦 package-lock.json has changed."
  echo "🚨 Please run npm install to bring your dependencies up to date."
  echo "------------------------------------------------------------------"
fi
